<?php
declare(strict_types=1);
if(!str_ends_with((string)getenv('DB_DATABASE'),'_admin_test'))throw new RuntimeException('Disposable test DB required');
define('BASE_PATH',dirname(__DIR__));require BASE_PATH.'/vendor/autoload.php';$c=require BASE_PATH.'/config/container.php';
Hyperf\Database\Model\Register::setConnectionResolver($c->get(Hyperf\Database\ConnectionResolverInterface::class));
if(!class_exists(App\Service\AdminArticleBatchService::class)){echo "FAIL batch service missing\n";exit(1);}
$failed=false;Swoole\Coroutine\run(function()use(&$failed){
 $pdo=new PDO('mysql:host='.getenv('DB_HOST').';dbname='.getenv('DB_DATABASE'),getenv('DB_USERNAME'),getenv('DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
 $pdo->exec('DROP TABLE IF EXISTS hotspots');
 $pdo->exec("CREATE TABLE hotspots (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(191),title VARCHAR(191),summary TEXT,status VARCHAR(16) DEFAULT 'published',period VARCHAR(64) DEFAULT '',priority VARCHAR(2) DEFAULT 'A',level VARCHAR(2) DEFAULT 'A',type VARCHAR(32) DEFAULT '',tag VARCHAR(32) DEFAULT '',subject_id INT DEFAULT 1,html LONGTEXT,outline JSON,word_count INT DEFAULT 0,markdown LONGTEXT,revision INT DEFAULT 1,content_source VARCHAR(16) DEFAULT 'dataset',comment_mode VARCHAR(16) DEFAULT 'open',created_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB");
 $pdo->exec("DELETE FROM article_revisions WHERE type='hotspot'");
 $pdo->exec("CREATE TABLE IF NOT EXISTS admin_audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,admin_id BIGINT UNSIGNED,action VARCHAR(64),target_type VARCHAR(32),target_id VARCHAR(64),detail JSON,created_at DATETIME) ENGINE=InnoDB");
 $pdo->exec("UPDATE users SET role='admin',status='active' WHERE id=1");App\Support\Auth::setUser(App\Model\User::find(1));
 $articles=new App\Service\AdminArticleService(new App\Service\ArticleRenderer());$batch=new App\Service\AdminArticleBatchService($articles,new App\Service\AdminAuditService());
 $one=$articles->save('hotspot',['title'=>'批量甲','format'=>'markdown','body'=>'# 甲']);$two=$articles->save('hotspot',['title'=>'批量乙','format'=>'markdown','body'=>'# 乙']);
 $n=0;$errors=[];$assert=fn($ok,$m)=>$ok?:throw new RuntimeException($m);$check=function($name,$fn)use(&$n,&$errors){try{$fn();++$n;echo"PASS $name\n";}catch(Throwable$e){$errors[]=$name.': '.$e->getMessage();echo'FAIL '.end($errors)."\n";}};
 $check('partial status batch reports conflict and exact successes',function()use($batch,$articles,$one,$two,$assert){$r=$batch->updateStatus('hotspot',['status'=>'hidden','items'=>[['id'=>$one->id,'expectedRevision'=>1],['id'=>$two->id,'expectedRevision'=>999]]]);$assert($r['succeeded']===1&&$r['failed']===1&&$r['results'][1]['status']===409,'wrong partial results');$assert($articles->detail('hotspot',$one->id)['status']==='hidden'&&$articles->detail('hotspot',$two->id)['status']==='published','wrong partial writes');});
 $check('batch rejects duplicate invalid entries before any write',function()use($batch,$articles,$one,$assert){$before=$articles->detail('hotspot',$one->id);foreach([['status'=>'published','items'=>[['id'=>$one->id,'expectedRevision'=>2],['id'=>$one->id,'expectedRevision'=>2]]],['status'=>'draft','items'=>[['id'=>$one->id,'expectedRevision'=>2]]]]as$data){try{$batch->updateStatus('hotspot',$data);}catch(RuntimeException$e){$assert($e->getCode()===422,'invalid code');continue;}throw new RuntimeException('invalid batch accepted');}$assert($articles->detail('hotspot',$one->id)===$before,'preflight wrote data');});
 $check('missing batch record is isolated from valid record',function()use($batch,$two,$assert){$r=$batch->updateStatus('hotspot',['status'=>'hidden','items'=>[['id'=>2147483647,'expectedRevision'=>1],['id'=>$two->id,'expectedRevision'=>1]]]);$assert($r['succeeded']===1&&$r['results'][0]['status']===404,'missing row not isolated');});
 $check('audit insert failure rolls back status and history',function()use($batch,$articles,$one,$pdo,$assert){$before=$articles->detail('hotspot',$one->id);$count=$pdo->query("SELECT COUNT(*) FROM article_revisions WHERE type='hotspot' AND article_id=".$one->id)->fetchColumn();$pdo->exec("CREATE TRIGGER reject_batch_audit BEFORE INSERT ON admin_audit_logs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='injected audit failure'");try{$r=$batch->updateStatus('hotspot',['status'=>'published','items'=>[['id'=>$one->id,'expectedRevision'=>2]]]);}finally{$pdo->exec('DROP TRIGGER reject_batch_audit');}$assert($r['failed']===1&&$articles->detail('hotspot',$one->id)===$before,'failed operation persisted');$assert($pdo->query("SELECT COUNT(*) FROM article_revisions WHERE type='hotspot' AND article_id=".$one->id)->fetchColumn()===$count,'history persisted');});
 $check('batch cannot be called without fresh admin',function()use($batch,$one,$assert){App\Support\Auth::setUser(null);try{$batch->updateStatus('hotspot',['status'=>'published','items'=>[['id'=>$one->id,'expectedRevision'=>2]]]);}catch(RuntimeException$e){$assert($e->getCode()===403,'wrong auth code');return;}throw new RuntimeException('unauthorized batch accepted');});
 echo "RESULT $n passed, ".count($errors)." failed\n";$failed=$errors!==[];
});exit($failed?1:0);
