<?php
declare(strict_types=1);
if(!str_ends_with((string)getenv('DB_DATABASE'),'_admin_test'))throw new RuntimeException('Disposable test database required');
$pdo=new PDO('mysql:host='.getenv('DB_HOST').';dbname='.getenv('DB_DATABASE'),getenv('DB_USERNAME'),getenv('DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);
$pdo->prepare("INSERT INTO user_tokens (user_id,token_hash,user_agent,expires_at,created_at,updated_at) VALUES (1,?,'local-runtime-test',DATE_ADD(NOW(),INTERVAL 10 MINUTE),NOW(),NOW())")->execute([$hash]);
$http=function($path,$expected,$method='GET',$body=null,$authenticated=true)use($token){
 $context=stream_context_create(['http'=>['method'=>$method,'timeout'=>10,'ignore_errors'=>true,'header'=>"Content-Type: application/json\r\nConnection: close\r\n".($authenticated?"Authorization: Bearer $token\r\n":''),'content'=>$body===null?'':json_encode($body)]]);
 $raw=file_get_contents('http://127.0.0.1:9501/api/v1'.$path,false,$context);preg_match('/HTTP\/\S+ (\d+)/',$http_response_header[0]??'',$matches);$status=(int)($matches[1]??0);
 if($status!==$expected)throw new RuntimeException("$method $path expected $expected got $status: $raw");
 $result=json_decode($raw,true);if(!is_array($result))throw new RuntimeException('Invalid runtime JSON');echo "PASS HTTP $method $path $status\n";return$result;
};
try {
 $http('/auth/me',200);
 $http('/admin/hotspots',200);
 $http('/admin/hotspots/1',200);
 $preview=$http('/admin/articles/preview',200,'POST',['format'=>'markdown','body'=>"# HTTP标题\n\n**安全正文**"]);
 if(!str_contains($preview['data']['html'],'toc-0'))throw new RuntimeException('Runtime renderer not wired');
 $http('/admin/articles/hotspot/1/revisions',200);
 $http('/admin/articles/hotspot/1/export',200);
 $http('/admin/articles/hotspot/1/source-diff',200);
 $http('/admin/articles/hotspot/source-diff',200);
 $http('/admin/overview?from=2026-10-10&to=2026-10-10',200);
 $http('/admin/audit-logs',200);
 $students=$http('/admin/mistakes/students?q=S125&page=999',200);
 if($students['data']['total']!==1||$students['data']['page']!==1)throw new RuntimeException('Runtime student filters not wired');
 $items=$http('/admin/mistakes/students/S001/items?module='.rawurlencode('马原').'&errorType='.rawurlencode('审题失误'),200);
 if($items['data']['total']!==20||count($items['data']['filters']['modules'])!==3)throw new RuntimeException('Runtime item filters not wired');
 $http('/admin/mistakes/students/missing/items',404);
 $http('/admin/mistakes/students?q%5B%5D=bad',422);
 $comments=$http('/admin/comments?q='.rawurlencode('评论31').'&userId=2&articleSlug=article-1',200);
 if($comments['data']['total']!==1||$comments['data']['items'][0]['id']!==31)throw new RuntimeException('Runtime comment filters not wired');
 $http('/admin/comments?userId=0',422);
 $http('/admin/comments?status=unknown',422);
 $http('/admin/comments',401,'GET',null,false);
 $http('/admin/questions/900',200);
 $created=$http('/admin/papers/editor-paper/questions',201,'POST',['no'=>90,'type'=>'single','stem'=>'HTTP题干','options'=>['A'=>'A','H'=>'H'],'answer'=>'H','score'=>2,'sortOrder'=>-30]);
 $questionId=$created['data']['id'];
 $updated=$http('/admin/questions/'.$questionId,200,'PATCH',['expectedRevision'=>1,'options'=>['A'=>'新A','H'=>'新H']]);
 if($updated['data']['revision']!==2||array_keys($updated['data']['options'])!==['A','H'])throw new RuntimeException('Runtime question keys/revision not preserved');
 $http('/admin/questions/'.$questionId,409,'PATCH',['expectedRevision'=>1,'stem'=>'过期正文']);
 $http('/admin/questions/'.$questionId,422,'PATCH',['expectedRevision'=>2,'pid'=>'other']);
 $http('/admin/papers/editor-paper/questions',409,'POST',['no'=>90,'type'=>'single','stem'=>'重复题','options'=>['A'=>'A','H'=>'H'],'answer'=>'H']);
 $http('/admin/questions/999999',404);
 $mock=$http('/admin/mocks/library-mock?page=999&perPage=20',200);
 if($mock['data']['questions']['page']!==7||$mock['data']['questions']['total']!==125||$mock['data']['mock']['sourceFile']!=='source.docx')throw new RuntimeException('Runtime mock detail paging/source missing');
 $predictions=$http('/admin/predictions?page=999&perPage=20',200);
 if($predictions['data']['page']!==7||!isset($predictions['data']['items'][0]['sortOrder']))throw new RuntimeException('Runtime prediction page/sort missing');
 $prediction=$http('/admin/predictions/1',200,'PATCH',['sortOrder'=>-100]);
 if($prediction['data']['sortOrder']!==-100||$prediction['data']['status']!=='hidden'||$prediction['data']['commentMode']!=='closed')throw new RuntimeException('Runtime prediction changed visibility');
 $http('/admin/predictions/1',422,'PATCH',['sortOrder'=>1.2]);
 $http('/admin/questions/900',401,'GET',null,false);
 $encodedPid='试卷 %2F';$encodedPaperPath='/admin/papers/'.rawurlencode($encodedPid).'/questions';
 $empty=$http($encodedPaperPath,200);
 if($empty['data']['nextNo']!==1||$empty['data']['total']!==0)throw new RuntimeException('Encoded paper path did not resolve exact empty paper');
 $encodedCreated=$http($encodedPaperPath,201,'POST',['no'=>1,'type'=>'single','stem'=>'编码试卷题干','options'=>['A'=>'A','H'=>'H'],'answer'=>'H']);
 if($encodedCreated['data']['pid']!==$encodedPid)throw new RuntimeException('Encoded PID decoded twice during question creation');
 $encodedQuestionId=$encodedCreated['data']['id'];
 $encodedDetail=$http('/admin/questions/'.$encodedQuestionId,200);
 if($encodedDetail['data']['pid']!==$encodedPid)throw new RuntimeException('Encoded PID changed in persisted question detail');
 $encodedUpdated=$http('/admin/questions/'.$encodedQuestionId,200,'PATCH',['expectedRevision'=>1,'stem'=>'编码试卷题干更新']);
 if($encodedUpdated['data']['pid']!==$encodedPid||$encodedUpdated['data']['revision']!==2)throw new RuntimeException('Encoded PID changed during question update');
 $http('/admin/articles/hotspot/status-batch',422,'POST',['status'=>'draft','items'=>[]]);
 $http('/admin/articles/preview',401,'POST',['format'=>'markdown','body'=>'denied'],false);
 echo "LOCAL_RUNTIME_HTTP_SMOKE_COMPLETE\n";
} finally {$pdo->prepare('DELETE FROM user_tokens WHERE token_hash=?')->execute([$hash]);}
